In [18]:
import pandas as pd
from fastai.vision.all import *

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from anyio import Path


df_path= Path('/content/drive/MyDrive/sports.csv')
zip_path = Path('/content/drive/MyDrive/sports_archive.zip')  #the path where the training images are stored
extract_path = Path('/content/drive/MyDrive/sports_archive')  #the path where the training images will be extracted to


df = pd.read_csv(df_path)

In [21]:
df.head()

   class id                 filepaths      labels data set
0         0  train/air hockey/001.jpg  air hockey    train
1         0  train/air hockey/002.jpg  air hockey    train
2         0  train/air hockey/003.jpg  air hockey    train
3         0  train/air hockey/004.jpg  air hockey    train
4         0  train/air hockey/005.jpg  air hockey    train

Renaming the column names

In [22]:
df.columns = df.columns.str.replace(' ', '_').str.lower()
df.head()

   class_id                 filepaths      labels data_set
0         0  train/air hockey/001.jpg  air hockey    train
1         0  train/air hockey/002.jpg  air hockey    train
2         0  train/air hockey/003.jpg  air hockey    train
3         0  train/air hockey/004.jpg  air hockey    train
4         0  train/air hockey/005.jpg  air hockey    train

In [ ]:
datablock = DataBlock(blocks=(ImageBlock, CategoryBlock),
                   splitter=ColSplitter('data_set'),   #based on the column 'data_set' in the dataframe, we are splitting the datas
                   get_x=ColReader('filepaths',pref=extract_path/'/'),   #the source of the data is the path to the images
                   get_y=ColReader('labels'),
                   item_tfms = [Resize(192, method = 'squish')],
                   batch_tfms=aug_transforms()
                   )

In [24]:
dls = datablock.dataloaders(df)
dls.show_batch()

IndexError: single positional indexer is out-of-bounds